### ISSUE TITLE
Autocomplete not working when special chars are present

### ISSUE THREAD

**Issue by masakik** [modus75/piwigo-autocomplete#1]
Hi, When in albums there are words like "aniversário" with "á" and other special chars the autocomplete do not use it. I have already tried to invalidate the cache but it did not work.

**Comment by modus75** [comment]
Normally most diacritics are correctly handled. can I have a link to the site?

**Comment by masakik** [comment]
Sorry for delay. I could not reproduce the issue to show you. Instead I noticed an strange behaviour: attached the print screens shows when I´m typing on search box it changes hints not narrowing but expanding for different ones. Also I put a word between parenthesis like this (en) and it coud not find if I search for 'en'.

**Comment by modus75** [comment]
Sorry. I cannot see any screenshot. Please open a discussion on the forum as the initial bug report cannot be reproduced

**Comment by masakik** [comment]
Thanks,
